######################################################################
# Automatically generated by qmake (3.0) Joi ian. 4 15:13:34 2018
######################################################################

TEMPLATE = app
TARGET = ConnectFour
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += mainmenu.h mainwindow.h
FORMS += mainmenu.ui mainwindow.ui
SOURCES += main.cpp mainmenu.cpp mainwindow.cpp
